services:
  - type: web
    name: traquementophp
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: FILESYSTEM_DISK
        value: local
      - key: REDIS_ENABLED
        value: true
      - key: REDIS_HOST
        value: redis-17623.c74.us-east-1-4.ec2.redns.redis-cloud.com
      - key: REDIS_PASSWORD
        value: TGT9TZNhbBTr0mlmpFlCFQMVKqJAXOoB
      - key: REDIS_PORT
        value: 17623
      - key: PORT
        value: 8080
      - key: RENDER
        value: true
      - key: RENDER_DATABASE_URL
        fromDatabase:
          name: traquementophp-db
          property: connectionString
    buildCommand: |
      set -e
      echo "[BuildCommand] Iniciando..."
      
      echo "[BuildCommand] Verificando existência do arquivo GeoIP..."
      if [ -f "storage/app/geoip/GeoLite2-City.mmdb" ]; then
        echo "[BuildCommand] GeoLite2-City.mmdb encontrado em storage/app/geoip/."
      else
        echo "[BuildCommand] ALERTA: GeoLite2-City.mmdb NÃO encontrado em storage/app/geoip/ após COPY . ."
        echo "[BuildCommand] Certifique-se que o arquivo está comitado no Git e não está no .gitignore."
      fi
      
      echo "[BuildCommand] Executando otimizações e migrações Laravel..."
      php artisan config:cache && \
      php artisan route:cache && \
      php artisan view:cache && \
      php artisan event:cache && \
      php artisan migrate:fresh --force --seed
      echo "[BuildCommand] Otimizações e migrações Laravel concluídas."
    startCommand: /usr/local/bin/start.sh

databases:
  - name: traquementophp-db
    plan: starter
    type: postgres
    ipAllowList: [] 